Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
selectYear = mas.select_year( year_min=1897, year_max=1940, state = 'gs' )
print('A:',selectYear.sel_A)
print('Z:',selectYear.sel_Z)
print('N:',selectYear.sel_N)
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[8][39m[32m, line 1[39m
[32m----> [39m[32m1[39m selectYear = [43mmas[49m[43m.[49m[43mselect_year[49m[43m([49m[43m [49m[43myear_min[49m[43m=[49m[32;43m1897[39;49m[43m,[49m[43m [49m[43myear_max[49m[43m=[49m[32;43m1940[39;49m[43m,[49m[43m [49m[43mstate[49m[43m [49m[43m=[49m[43m [49m[33;43m'[39;49m[33;43mgs[39;49m[33;43m'[39;49m[43m [49m[43m)[49m
[32m      2[39m [38;5;28mprint[39m([33m'[39m[33mA:[39m[33m'[39m,selectYear.sel_A)
[32m      3[39m [38;5;28mprint[39m([33m'[39m[33mZ:[39m[33m'[39m,selectYear.sel_Z)

[36mFile [39m[32m/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nucleardatapy/nuc/setup_be_exp.py:665[39m, in [36msetupBEExp.select_year[39m[34m(self, year_min, year_max, state)[39m
[32m    652[39m [38;5;250m[39m[33;03m"""[39;00m
[32m    653[39m [33;03mMethod which select some nuclei from the table according to the discovery year.[39;00m
[32m    654[39m 
[32m   (...)[39m[32m    662[39m [33;03m**Attributes:**[39;00m
[32m    663[39m [33;03m"""[39;00m
[32m    664[39m [38;5;66;03m#[39;00m
[32m--> [39m[32m665[39m [38;5;28;01mif[39;00m [38;5;28;43mself[39;49m[43m.[49m[43myear[49m [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[32m    666[39m     [38;5;28mprint[39m([33m'[39m[33mThere is no year in the experimental mass table[39m[33m'[39m)
[32m    667[39m     [38;5;28mprint[39m([33m'[39m[33mTable:[39m[33m'[39m,[38;5;28mself[39m.table)

[31mAttributeError[39m: 'setupBEExp' object has no attribute 'year'

