Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/asyncio/base_events.py", line 691, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.12.10/x64/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# reference band:
den = np.array([0.04,0.06,0.08,0.1,0.12,0.14,0.16])
bmodels = [ '2016-MBPT-AM', '2016-QMC-NM', '2020-MBPT-AM' ]
band = nuda.matter.setupMicroBand( bmodels, den=den, matter='NM'  )
# plot:
models, models_lower = nuda.matter.pheno_models()
print('models:',models)
for model in models:
    print('model:',model)
    nuda.fig.matter_setupPheno_E_fig( None, model, band, 'NM' )
------------------

----- stdout -----

Band in NM
model ->  2016-MBPT-AM
model ->  2016-QMC-NM
model ->  2020-MBPT-AM
model ->  2016-MBPT-AM
model ->  2016-QMC-NM
model ->  2020-MBPT-AM
models: ['Skyrme', 'ESkyrme', 'Gogny', 'Fayans', 'NLRH', 'DDRH', 'DDRHF']
model: Skyrme
------------------

[31m---------------------------------------------------------------------------[39m
[31mTypeError[39m                                 Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[10][39m[32m, line 10[39m
[32m      8[39m [38;5;28;01mfor[39;00m model [38;5;129;01min[39;00m models:
[32m      9[39m     [38;5;28mprint[39m([33m'[39m[33mmodel:[39m[33m'[39m,model)
[32m---> [39m[32m10[39m     [43mnuda[49m[43m.[49m[43mfig[49m[43m.[49m[43mmatter_setupPheno_E_fig[49m[43m([49m[43m [49m[38;5;28;43;01mNone[39;49;00m[43m,[49m[43m [49m[43mmodel[49m[43m,[49m[43m [49m[43mband[49m[43m,[49m[43m [49m[33;43m'[39;49m[33;43mNM[39;49m[33;43m'[39;49m[43m [49m[43m)[49m

[31mTypeError[39m: matter_setupPheno_E_fig() takes 3 positional arguments but 4 were given

